sudo: false
language: elixir
elixir:
  - 1.6
  - 1.7
otp_release:
  - 21.0
script:
  - "mix do deps.get, compile-check"
  - "MIX_ENV=test mix do deps.get, mix test"
notifications:
  recipients:
    - paulschoenfelder@gmail.com
